### ISSUE TITLE
How to update data without resetting the axis limits

### ISSUE THREAD

**Issue by HowardWhile** [swharden/ScottPlot#432]
Hi 
This is my ScottPlot version 
![image](https://user-images.githubusercontent.com/18715360/82998626-8d74a280-a03a-11ea-88b2-3e1e29de7607.png)

I have no idea to disable automatic fit when keep render.
I hope to check the signal details while chart drawing.
But the plot will keep fit to data automatic.
Like below FFT_X:

![p03](https://user-images.githubusercontent.com/18715360/82997685-49cd6900-a039-11ea-8a43-466d4b684ecd.gif)

---

I hope the effect is like your previous project [Realtime Microphone FFT with ScottPlot](https://github.com/swharden/Csharp-Data-Visualization/tree/master/projects/18-09-19_microphone_FFT_revisited).

![p01](https://user-images.githubusercontent.com/18715360/82998339-3242b000-a03a-11ea-9865-332d19ee6a8f.gif)
Hope to achieve the effect by laste ScottPlot v4.0.34, 
Instead of `ScottPlot.ScottPlotUC` in previous project.

---

**This is what I have tried:**
```cs
double[] fft_result = this.my_fft(src_wave);
var plt = this.chart_fft.plt;
plt.Clear();
plt.PlotSignal(fft_result, sample_rate, label: "FFT_X") ;
plt.Legend();
this.chart_fft.Render();
```

**Comment by swharden** [comment]
Hey @HowardWhile 

The issue is that you are clearing the plot and re-plotting every time. The fix is to plot just once, change the data inside the array as needed, and call for a render whenever the underlying data changed. In other words the `fft_result` should only be `new`'d once.

```cs
// put this in your startup sequence
double[] fft_result = new double[someLength];
formsPlot1.plt.PlotSignal(fft_result, sample_rate, label: "FFT_X") ;
formsPlot1.plt.Legend();
```

```cs
// when new data comes in, analyze it, and re-render the plot
fft_result = this.my_fft(src_wave);
formsPlot1.Render();
```

Let me know if this doesn't do the trick! 👍

**Comment by StendProg** [comment]
> // call this whenever new data is ready
fft_result = this.my_fft(src_wave);
formsPlot1.Render();

I don't try it, but i think it will not work.
There is 2 way to update `PlottableSignal` data:
1. Update internal `ys` reference which means you should store `PlottableSignal` in init section like:
```c#
PlottableSignal pSignal = formsPlot.plt.PlotSignal(fft_result, sample_rate, label: "FFT_X");
```
and then update internal reference inside you animation loop like:
```c#
// call this whenever new data is ready
pSignal.ys = this.my_fft(src_wave);
formsPlot1.Render();
```

2. do the same like @swharden  pointed, but instead update reference, you need to copy each element:
```c#
// call this whenever new data is ready
var current_result = this.my_fft(src_wave);
for (int i = 0; i < fft_result.Length; i++)
{
    fft_result[i] = current_result[i];
}
formsPlot1.Render();
```

**Comment by swharden** [comment]
Thanks for noticing this @StendProg! I definitely described the implementation incorrectly.

This is the problem with browser-window programming 😅 

Here is the code for the "live updating data" used in the demo application. It uses the method described by @StendProg's second solution:
https://github.com/swharden/ScottPlot/blob/641126646d77c3aefad055e9f31d44da333eb03f/src/ScottPlot.Demo.WinForms/WinFormsDemos/LiveDataUpdate.cs#L13-L38

Notice the array that's plotted (`liveData`) is stored at the class level. This is what allows its contents to be updated, and calling for a render will always display its current contents.

**Comment by HowardWhile** [comment]
Thanks for your help @StendProg @swharden
It helped me a lot, and achieve the effect I want.

![08](https://user-images.githubusercontent.com/18715360/83119067-d3486e00-a101-11ea-9d70-d87ee4a772d0.gif)

---

But I encountered some problems in the process of writing program.
When the length of `ys` and value of `sampleRate` change.

I am follow @StendProg suggest 1, initial the formsPlot 

```cs
double[] sin = ScottPlot.DataGen.Sin(50, 2);
this.fft_plt_signal = this.chart_fft.plt.PlotSignal(sin, 1000);
this.chart_fft.Render();
```
Result like below.

![image](https://user-images.githubusercontent.com/18715360/83104456-6033fd00-a0eb-11ea-8a8f-a19a486be8a7.png)

---
and then update internal `ys`  in animation loop.
```cs
this.fft_plt_signal.ys = my_fft(src_wave);
this.chart_fft.Render(); 
```
`chart_fft` only shows part of the result. 
Even if the `ys` number has increased to 1558.

![image](https://user-images.githubusercontent.com/18715360/83106056-611a5e00-a0ee-11ea-9e56-6615b15c8326.png)

So I modify `maxRenderIndex`  to fit `ys.length`. 
```cs
this.fft_plt_signal.ys = my_fft(src_wave);
this.fft_plt_signal.maxRenderIndex = this.fft_plt_signal.ys.Length; // here
// this.fft_plt_signal.maxRenderIndex = this.fft_plt_signal.ys.Length - 1; // Maybe this is the correct
this.chart_fft.Render(); 
```
**I am not sure this way is incorrect**,
 but now the `formsPlot` can render all the `ys`.

![image](https://user-images.githubusercontent.com/18715360/83110118-2962e480-a0f5-11ea-9157-8afead3813de.png)

---

Last I want to change the `sampleRate` 
```cs
this.fft_plt_signal.ys = my_fft(src_wave);
this.fft_plt_signal.maxRenderIndex = this.fft_plt_signal.ys.Length;
this.fft_plt_signal.sampleRate = 1.0; // here
this.chart_fft.Render(); 
```
But the x axis tick value has not changed. 
Correctly it should become 0 - 5000.
When `point number = 5000, sampleRate = 1`


![image](https://user-images.githubusercontent.com/18715360/83112965-89f42080-a0f9-11ea-85a5-e7d43bbf0c01.png)

I must also change `samplePeriod` when update `sampleRate`
```cs
this.fft_plt_signal.ys = my_fft(src_wave);
this.fft_plt_signal.maxRenderIndex = this.fft_plt_signal.ys.Length;

this.fft_plt_signal.sampleRate = 1.0; 
this.fft_plt_signal.samplePeriod = 1.0 / this.fft_plt_signal.sampleRate; // here

this.chart_fft.Render(); 
```
![image](https://user-images.githubusercontent.com/18715360/83113876-cc6a2d00-a0fa-11ea-9215-364b7872df66.png)

Maybe these two values can change at same time by encapsulation.
I think it can be modified like below:
![image](https://user-images.githubusercontent.com/18715360/83116143-f2450100-a0fd-11ea-9bff-4169d55e6b5a.png)

---

**Comment by swharden** [comment]
> Thanks for your help @StendProg @swharden
> It helped me a lot, and achieve the effect I want.

Hi @HowardWhile I'm happy to see you got this working! I'm curious to know a little more about your application. What signal are you measuring?

Coincidentally I've been working on two FFT-related projects this week:
* https://github.com/swharden/FftSharp
* https://github.com/swharden/Spectrogram

I can't help but ask - why is the size of your array changing? You could get a huge performance improvement if you don't create a whole new array in memory with every frame you draw on the screen. It seems like your input signal is a fixed size, so the FFT output (periodogram / power spectral density) should also be a fixed size. Even if your input array is "growing" (less than the expected size) it can be padded with zeros prior to calculating the FFT so all arrays are fixed-size and don't have to be recreated and garbage collected frequently. So, while your current solution works, I wanted to suggest double-checking to make sure all those `new` statements you must be doing are really necessary. Further, if your input array size really is changing with every iteration, your FFT algorithm may be zero-padding your input data anyway to achieve a fixed size, since the FFT algorithm requires an input array with a length that is an even power of 2. Just a thought!

### Updating sampleRate and Sample Period

> But I encountered some problems in the process of writing program.
> When the length of `ys` or value of `sampleRate` change.

Thanks for mentioning this! The problem, as you found, is that `samplePeriod` is calculated in the initializer and is not properly updated if you update `sampleRate`.

https://github.com/swharden/ScottPlot/blob/641126646d77c3aefad055e9f31d44da333eb03f/src/ScottPlot/plottables/PlottableSignal.cs#L39-L40

A good solution, as suggested by your screenshot, is to use properties so updating one updates the other too. This is a very good idea!

### maxRenderIndex

Similarly, you noted that `maxRenderIndex` is being calculated (and matched to `ys.Length`) in the initializer, and this doesn't account for a situation where the user sets a differently sized `ys` later. The best solution here is to move this size check to inside the render loop.

https://github.com/swharden/ScottPlot/blob/641126646d77c3aefad055e9f31d44da333eb03f/src/ScottPlot/plottables/PlottableSignal.cs#L48-L49

Thank you for these suggestions, and the excellent animated screenshots. They are very helpful! I'll implement these ideas this weekend.

**Comment by HowardWhile** [comment]
Hi @swharden 

>Hi @HowardWhile I'm happy to see you got this working! I'm curious to know a little more about your application. What signal are you measuring?

The signal  source is acceleration from accelerometer. sample rate is 1k hz.
I'm planning to analyze motor vibration. And determine "how health" of the motor.

>  why is the size of your array changing? ... It seems like your input signal is a fixed size, so the FFT output (periodogram / power spectral density) should also be a fixed size. 

Actually I do not fixed the input signal size. I designed to allow users choose the range to calculate FFT. It may be 1 second, 10 seconds, or other range, depends on the analysis needs.

![02](https://user-images.githubusercontent.com/18715360/83222680-7a351480-a1ab-11ea-8f6e-089a52e437f7.gif)

![01](https://user-images.githubusercontent.com/18715360/83222849-ed3e8b00-a1ab-11ea-9671-fd334697293b.gif)

---

Thanks for your reminder about performance. Maybe I will start check the performance impact of non-fixed signal.

BTW This is my tool for calculating FFT  `MathNet.Numerics` [gist] https://gist.github.com/HowardWhile/c6a372b0d724486ea0532564465edd50).
I am also very interested in your `Spectrogram` project.

**Comment by swharden** [comment]
> Actually I do not fixed the input signal size. I designed to allow users choose the range to calculate FFT. It may be 1 second, 10 seconds, or other range, depends on the analysis needs.

Ah, that makes sense. Thanks for sharing the animated screenshots - this is a really cool application! I can see from the benchmark performance is fantastic so it looks like what you're doing is working great. 

The gist is also helpful in reviewing how MathNet.Numerics handles FFT

Thanks for sharing!
